import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Copy, Search } from 'lucide-react';
import { tools } from '../lib/tool-catalog';

const copy=(v:string)=>navigator.clipboard?.writeText(v);
function Output({value}:{value:string}){return <div className="output">{value||'—'}<button className="copy-btn" onClick={()=>copy(value)}><Copy size={13}/> Copy</button></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function Num({label,value,set,step=1}:{label:string;value:number;set:(n:number)=>void;step?:number}){return <Field label={label}><input type="number" step={step} value={value} onChange={e=>set(Number(e.target.value))}/></Field>}
function Split({left,right}:{left:React.ReactNode;right:React.ReactNode}){return <div className="grid-2"><div className="card">{left}</div><div className="card">{right}</div></div>}
const rgb=(h:string)=>{const n=h.replace('#','');return{r:parseInt(n.slice(0,2),16)||0,g:parseInt(n.slice(2,4),16)||0,b:parseInt(n.slice(4,6),16)||0}};

function Favicon(){const[t,setT]=useState('IT'),[bg,setBg]=useState('#183424'),[fg,setFg]=useState('#F3EDDC');const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="${bg}"/><text x="32" y="40" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700" fill="${fg}">${t.replace(/[<>&]/g,'')}</text></svg>`;return <Split left={<><Field label="Initials"><input maxLength={3} value={t} onChange={e=>setT(e.target.value)}/></Field><Field label="Background"><input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></Field><Field label="Text"><input type="color" value={fg} onChange={e=>setFg(e.target.value)}/></Field><button className="primary-btn" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download='favicon.svg';a.click()}}>Download SVG</button></>} right={<><div dangerouslySetInnerHTML={{__html:svg}} style={{width:128,height:128,margin:'20px auto'}}/><Output value={svg}/></>}/>}
function SvgOptimizer(){const[i,setI]=useState('<svg width="24" height="24">\n  <!-- icon -->\n  <path fill="#000" d="M4 4h16v16H4z" />\n</svg>');const o=i.replace(/<!--([\s\S]*?)-->/g,'').replace(/>\s+</g,'><').replace(/\s{2,}/g,' ').replace(/\s+\/>/g,'/>').trim();return <Split left={<Field label="SVG"><textarea value={i} onChange={e=>setI(e.target.value)}/></Field>} right={<><div className="metric"><strong>{i?Math.max(0,Math.round((1-o.length/i.length)*100)):0}%</strong><span>smaller</span></div><div className="section-label">Optimized</div><Output value={o}/></>}/>}
function Shadow(){const[x,sx]=useState(0),[y,sy]=useState(14),[bl,sb]=useState(34),[sp,ss]=useState(-8),[op,so]=useState(.22),[c,sc]=useState('#183424'),r=rgb(c),v=`${x}px ${y}px ${bl}px ${sp}px rgba(${r.r},${r.g},${r.b},${op})`;return <Split left={<><Num label="X" value={x} set={sx}/><Num label="Y" value={y} set={sy}/><Num label="Blur" value={bl} set={sb}/><Num label="Spread" value={sp} set={ss}/><Field label={`Opacity ${op}`}><input type="range" min="0" max="1" step=".01" value={op} onChange={e=>so(+e.target.value)}/></Field><Field label="Color"><input type="color" value={c} onChange={e=>sc(e.target.value)}/></Field></>} right={<><div style={{height:190,display:'grid',placeItems:'center'}}><div style={{width:150,height:90,background:'#f7f1e3',boxShadow:v}}/></div><Output value={`box-shadow: ${v};`}/></>}/>}
function Regex(){const[p,sp]=useState('\\b[\\w.%+-]+@[\\w.-]+\\.[A-Za-z]{2,}\\b'),[f,sf]=useState('gi'),[t,st]=useState('hello@example.com and team@indietools.dev');let m:string[]=[];let err='';try{m=Array.from(t.matchAll(new RegExp(p,f.includes('g')?f:f+'g'))).map(x=>`${x[0]} @ ${x.index}`)}catch(e){err=e instanceof Error?e.message:'Invalid regex'}return <Split left={<><Field label="Pattern"><input value={p} onChange={e=>sp(e.target.value)}/></Field><Field label="Flags"><input value={f} onChange={e=>sf(e.target.value)}/></Field><Field label="Text"><textarea value={t} onChange={e=>st(e.target.value)}/></Field></>} right={err?<p>{err}</p>:<><div className="metric"><strong>{m.length}</strong><span>matches</span></div><div className="section-label">Matches</div><Output value={m.join('\n')}/></>}/>}
function Hash(){const[i,si]=useState('indieTools'),[a,sa]=useState('SHA-256'),[o,so]=useState('');useEffect(()=>{crypto.subtle.digest(a,new TextEncoder().encode(i)).then(h=>so(Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,'0')).join('')))},[i,a]);return <Split left={<><Field label="Input"><textarea value={i} onChange={e=>si(e.target.value)}/></Field><Field label="Algorithm"><select value={a} onChange={e=>sa(e.target.value)}><option>SHA-1</option><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></select></Field></>} right={<Output value={o}/>}/>}
function OG(){const[t,st]=useState('Build faster with indieTools'),[d,sd]=useState('Free browser-first utilities for builders.'),[u,su]=useState('https://indietools.dev'),[im,sim]=useState('');return <Split left={<><Field label="Title"><input value={t} onChange={e=>st(e.target.value)}/></Field><Field label="Description"><textarea value={d} onChange={e=>sd(e.target.value)}/></Field><Field label="URL"><input value={u} onChange={e=>su(e.target.value)}/></Field><Field label="Image URL"><input value={im} onChange={e=>sim(e.target.value)}/></Field></>} right={<div style={{border:'1px solid var(--line-strong)',background:'#f7f1e3'}}>{im&&<img src={im} alt="" style={{width:'100%',height:180,objectFit:'cover'}}/>}<div style={{padding:16}}><small>{u}</small><h3 style={{fontSize:18}}>{t}</h3><p>{d}</p></div></div>}/>}
function Meta(){const[t,st]=useState('indieTools'),[d,sd]=useState('Free tools for builders'),[u,su]=useState('https://example.com'),[im,sim]=useState('https://example.com/og.png');const o=`<title>${t}</title>\n<meta name="description" content="${d}">\n<link rel="canonical" href="${u}">\n<meta property="og:title" content="${t}">\n<meta property="og:description" content="${d}">\n<meta property="og:url" content="${u}">\n<meta property="og:image" content="${im}">\n<meta name="twitter:card" content="summary_large_image">`;return <Split left={<><Field label="Title"><input value={t} onChange={e=>st(e.target.value)}/></Field><Field label="Description"><textarea value={d} onChange={e=>sd(e.target.value)}/></Field><Field label="URL"><input value={u} onChange={e=>su(e.target.value)}/></Field><Field label="Image"><input value={im} onChange={e=>sim(e.target.value)}/></Field></>} right={<Output value={o}/>}/>}
function Robots(){const[a,sa]=useState('/'),[d,sd]=useState('/admin\n/private'),[s,ss]=useState('https://example.com/sitemap.xml');const o=`User-agent: *\n${a.split('\n').filter(Boolean).map(v=>`Allow: ${v}`).join('\n')}\n${d.split('\n').filter(Boolean).map(v=>`Disallow: ${v}`).join('\n')}\n\nSitemap: ${s}`;return <Split left={<><Field label="Allow"><textarea value={a} onChange={e=>sa(e.target.value)}/></Field><Field label="Disallow"><textarea value={d} onChange={e=>sd(e.target.value)}/></Field><Field label="Sitemap"><input value={s} onChange={e=>ss(e.target.value)}/></Field></>} right={<Output value={o}/>}/>}
function JsonLd(){const[n,sn]=useState('indieTools'),[u,su]=useState('https://example.com'),[type,st]=useState('Organization');const data={'@context':'https://schema.org','@type':type,name:n,url:u};return <Split left={<><Field label="Type"><select value={type} onChange={e=>st(e.target.value)}><option>Organization</option><option>WebSite</option><option>SoftwareApplication</option></select></Field><Field label="Name"><input value={n} onChange={e=>sn(e.target.value)}/></Field><Field label="URL"><input value={u} onChange={e=>su(e.target.value)}/></Field></>} right={<Output value={`<script type="application/ld+json">\n${JSON.stringify(data,null,2)}\n</script>`}/>}/>}
function UTM(){const[u,su]=useState('https://example.com'),[src,ss]=useState('reddit'),[med,sm]=useState('social'),[cam,sc]=useState('launch'),[con,sco]=useState('');const o=useMemo(()=>{try{const x=new URL(u);[['utm_source',src],['utm_medium',med],['utm_campaign',cam],['utm_content',con]].forEach(([k,v])=>v&&x.searchParams.set(k,v));return x.toString()}catch{return'Invalid URL'}},[u,src,med,cam,con]);return <Split left={<><Field label="URL"><input value={u} onChange={e=>su(e.target.value)}/></Field><Field label="Source"><input value={src} onChange={e=>ss(e.target.value)}/></Field><Field label="Medium"><input value={med} onChange={e=>sm(e.target.value)}/></Field><Field label="Campaign"><input value={cam} onChange={e=>sc(e.target.value)}/></Field><Field label="Content"><input value={con} onChange={e=>sco(e.target.value)}/></Field></>} right={<Output value={o}/>}/>}
function Curl(){const[i,si]=useState("curl -X POST 'https://api.example.com/users' -H 'Content-Type: application/json' -d '{\"name\":\"Imad\"}'"),[mode,setMode]=useState('fetch');const p=parseCurl(i),o=p.error?p.error:mode==='fetch'?`fetch(${JSON.stringify(p.url)}, {\n  method: ${JSON.stringify(p.method)},\n  headers: ${JSON.stringify(p.headers,null,2)},${p.body?`\n  body: ${JSON.stringify(p.body)},`:''}\n});`:`axios({ url: ${JSON.stringify(p.url)}, method: ${JSON.stringify(p.method.toLowerCase())}, headers: ${JSON.stringify(p.headers,null,2)}${p.body?`, data: ${JSON.stringify(p.body)}`:''} });`;return <Split left={<><Field label="cURL"><textarea value={i} onChange={e=>si(e.target.value)}/></Field><div className="actions"><button className={mode==='fetch'?'primary-btn':'ghost-btn'} onClick={()=>setMode('fetch')}>Fetch</button><button className={mode==='axios'?'primary-btn':'ghost-btn'} onClick={()=>setMode('axios')}>Axios</button></div></>} right={<Output value={o}/>}/>}
function parseCurl(i:string){const url=i.match(/['"](https?:\/\/[^'"]+)['"]/)?.[1]||i.match(/https?:\/\/[^'"\s]+/)?.[0]||'';const method=i.match(/(?:-X|--request)\s+([A-Z]+)/i)?.[1]?.toUpperCase()||(/\s-d\s|--data/.test(i)?'POST':'GET');const headers:Record<string,string>={};for(const m of i.matchAll(/(?:-H|--header)\s+['"]([^:'"]+):\s*([^'"]+)['"]/g))headers[m[1]]=m[2];const body=i.match(/(?:-d|--data(?:-raw)?)\s+['"]([\s\S]*?)['"](?:\s|$)/)?.[1]||'';return{url,method,headers,body,error:url?'':'No URL found'}}
const CODES=[['200','OK','Request succeeded'],['201','Created','Resource created'],['204','No Content','No response body'],['301','Moved Permanently','Permanent redirect'],['302','Found','Temporary redirect'],['304','Not Modified','Cache still valid'],['400','Bad Request','Malformed request'],['401','Unauthorized','Authentication required'],['403','Forbidden','Not allowed'],['404','Not Found','Resource missing'],['409','Conflict','State conflict'],['422','Unprocessable Content','Validation failed'],['429','Too Many Requests','Rate limited'],['500','Internal Server Error','Unexpected server failure'],['502','Bad Gateway','Bad upstream response'],['503','Service Unavailable','Temporarily unavailable']];
function Status(){const[q,sq]=useState('');return <div className="card"><Field label="Search status"><input value={q} onChange={e=>sq(e.target.value)}/></Field><div style={{display:'grid',gap:8}}>{CODES.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase())).map(r=><div className="metric" key={r[0]}><strong>{r[0]} · {r[1]}</strong><span>{r[2]}</span></div>)}</div></div>}
function JsonPath(){const[i,si]=useState('{"user":{"name":"Imad","skills":["Java","React"]}}'),[p,sp]=useState('$.user.skills[0]');let o='';try{let c:any=JSON.parse(i);for(const raw of p.replace(/^\$\.?/,'').match(/[^.[\]]+|\[(\d+)\]/g)||[]){const m=raw.match(/^\[(\d+)\]$/);c=m?c[+m[1]]:c[raw]}o=JSON.stringify(c,null,2)}catch(e){o=e instanceof Error?e.message:'Invalid input'}return <Split left={<><Field label="JSON"><textarea value={i} onChange={e=>si(e.target.value)}/></Field><Field label="Path"><input value={p} onChange={e=>sp(e.target.value)}/></Field></>} right={<Output value={o}/>}/>}
function Headers(){const[i,si]=useState('content-type: application/json\ncache-control: no-store\nx-request-id: abc-123');const o:Record<string,string>={};i.split('\n').forEach(l=>{const x=l.indexOf(':');if(x>0)o[l.slice(0,x).trim().toLowerCase()]=l.slice(x+1).trim()});return <Split left={<Field label="Raw headers"><textarea value={i} onChange={e=>si(e.target.value)}/></Field>} right={<Output value={JSON.stringify(o,null,2)}/>}/>}
function Webhook(){const[p,sp]=useState('{"event":"payment.succeeded","id":"evt_123"}'),[s,ss]=useState('whsec_demo'),[o,so]=useState('');async function sign(){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(s),{name:'HMAC',hash:'SHA-256'},false,['sign']);const h=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(p));so(Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,'0')).join(''))}return <Split left={<><Field label="Payload"><textarea value={p} onChange={e=>sp(e.target.value)}/></Field><Field label="Secret"><input value={s} onChange={e=>ss(e.target.value)}/></Field><button className="primary-btn" onClick={sign}>Generate signature</button></>} right={<><div className="section-label">HMAC SHA-256</div><Output value={o}/><div className="section-label">Payload</div><Output value={(()=>{try{return JSON.stringify(JSON.parse(p),null,2)}catch{return'Invalid JSON'}})()}/></>}/>}
function Csv(){const[c,sc]=useState('name,email\nImad,imad@example.com\nSara,sara@example.com'),[j,sj]=useState('');const toJ=()=>{const l=c.trim().split(/\r?\n/),h=csvLine(l[0]||'');sj(JSON.stringify(l.slice(1).map(x=>Object.fromEntries(h.map((k,n)=>[k,csvLine(x)[n]??'']))),null,2))};const toC=()=>{try{const a=JSON.parse(j);const h=Object.keys(a[0]);sc([h.join(','),...a.map((x:any)=>h.map(k=>csvEsc(x[k])).join(','))].join('\n'))}catch{sc('Invalid JSON')}};return <div className="grid-2"><div className="card"><Field label="CSV"><textarea value={c} onChange={e=>sc(e.target.value)}/></Field><button className="primary-btn" onClick={toJ}>CSV → JSON</button></div><div className="card"><Field label="JSON"><textarea value={j} onChange={e=>sj(e.target.value)}/></Field><button className="ghost-btn" onClick={toC}>JSON → CSV</button></div></div>}
function csvLine(l:string){const a:string[]=[];let c='',q=false;for(let i=0;i<l.length;i++){if(l[i]==='"'&&l[i+1]==='"'&&q){c+='"';i++}else if(l[i]==='"')q=!q;else if(l[i]===','&&!q){a.push(c);c=''}else c+=l[i]}a.push(c);return a}const csvEsc=(v:any)=>/[",\n]/.test(String(v??''))?`"${String(v??'').replace(/"/g,'""')}"`:String(v??'');
function Yaml(){const[y,sy]=useState('name: indieTools\nprivate: true\ntools:\n  - json\n  - jwt'),[j,sj]=useState('');const parse=()=>{try{const o:any={};let key='';y.split('\n').forEach(r=>{if(/^\s+-\s/.test(r)&&key){if(!Array.isArray(o[key]))o[key]=[];o[key].push(scalar(r.replace(/^\s+-\s*/,'')));return}const m=r.match(/^([^:]+):\s*(.*)$/);if(!m)return;key=m[1].trim();o[key]=m[2].trim()?scalar(m[2].trim()):[]});sj(JSON.stringify(o,null,2))}catch{sj('Invalid YAML')}};const stringify=()=>{try{const o=JSON.parse(j);sy(Object.entries(o).map(([k,v])=>Array.isArray(v)?`${k}:\n${v.map(x=>`  - ${x}`).join('\n')}`:`${k}: ${typeof v==='object'?JSON.stringify(v):v}`).join('\n'))}catch{sy('Invalid JSON')}};return <div className="grid-2"><div className="card"><Field label="YAML"><textarea value={y} onChange={e=>sy(e.target.value)}/></Field><button className="primary-btn" onClick={parse}>YAML → JSON</button></div><div className="card"><Field label="JSON"><textarea value={j} onChange={e=>sj(e.target.value)}/></Field><button className="ghost-btn" onClick={stringify}>JSON → YAML</button></div></div>}
const scalar=(v:string)=>v==='true'?true:v==='false'?false:v==='null'?null:/^-?\d+(\.\d+)?$/.test(v)?Number(v):v.replace(/^['"]|['"]$/g,'');
function Xml(){const[x,sx]=useState('<user><name>Imad</name><role>developer</role></user>'),[j,sj]=useState('');const run=()=>{const d=new DOMParser().parseFromString(x,'application/xml');if(d.querySelector('parsererror'))return sj('Invalid XML');sj(JSON.stringify(xmlObj(d.documentElement),null,2))};return <Split left={<><Field label="XML"><textarea value={x} onChange={e=>sx(e.target.value)}/></Field><button className="primary-btn" onClick={run}>XML → JSON</button></>} right={<Output value={j}/>}/>}
function xmlObj(e:Element):any{const ch=Array.from(e.children);if(!ch.length)return e.textContent||'';const o:any={};ch.forEach(c=>{const v=xmlObj(c);o[c.tagName]=o[c.tagName]===undefined?v:Array.isArray(o[c.tagName])?[...o[c.tagName],v]:[o[c.tagName],v]});return{[e.tagName]:o}}
function Sql(){const[i,si]=useState("select id,name from users where active=true and created_at>now()-interval '30 days' order by created_at desc");const o=i.replace(/\s+/g,' ').replace(/\b(SELECT|FROM|WHERE|LEFT JOIN|RIGHT JOIN|INNER JOIN|JOIN|GROUP BY|ORDER BY|HAVING|LIMIT|VALUES|SET|AND|OR)\b/gi,m=>`\n${m.toUpperCase()}`).replace(/^\n/,'').trim();return <Split left={<Field label="SQL"><textarea value={i} onChange={e=>si(e.target.value)}/></Field>} right={<Output value={o}/>}/>}
function Fake(){const[n,sn]=useState(5),[seed,ss]=useState(42);const a=useMemo(()=>Array.from({length:Math.max(1,Math.min(100,n))},(_,i)=>{const x=seed+i*7919,f=['Alex','Sam','Maya','Noah','Lina','Omar','Eva','Leo'][x%8],l=['Martin','Smith','Bennani','Garcia','Kim','Brown','Lopez','Wilson'][Math.floor(x/7)%8];return{id:i+1,name:`${f} ${l}`,email:`${f}.${l}${x%97}@example.com`.toLowerCase(),active:x%3!==0,score:x%101}}),[n,seed]);return <Split left={<><Num label="Rows" value={n} set={sn}/><Num label="Seed" value={seed} set={ss}/></>} right={<Output value={JSON.stringify(a,null,2)}/>}/>}
function Calc({kind}:{kind:string}){const[a,sa]=useState(kind==='mrr'?49:kind==='arr'?5000:kind==='churn'?100:kind==='ltv'?49:kind==='pricing'?29:kind==='stripe'?100:5000),[b,sb]=useState(kind==='mrr'?100:kind==='arr'?12:kind==='churn'?5:kind==='ltv'?5:kind==='pricing'?100:kind==='stripe'?2.9:79),[c,sc]=useState(kind==='pricing'?20:kind==='stripe'?0.3:3000);let la='',lb='',lc='',o='';if(kind==='mrr'){la='Monthly price';lb='Customers';o=money(a*b)}if(kind==='arr'){la='MRR';lb='Months';o=money(a*b)}if(kind==='churn'){la='Customers at start';lb='Customers lost';o=`${a?((b/a)*100).toFixed(2):0}%`}if(kind==='ltv'){la='ARPU / month';lb='Monthly churn %';o=money(b?a/(b/100):0)}if(kind==='pricing'){la='Price / month';lb='Customers';lc='Monthly fixed costs';o=`MRR: ${money(a*b)}\nNet: ${money(a*b-c)}`}if(kind==='stripe'){la='Payment amount';lb='Fee %';lc='Fixed fee';const f=a*b/100+c;o=`Fee: ${money(f)}\nNet: ${money(a-f)}`}if(kind==='break-even'){la='Monthly fixed costs';lb='Revenue / customer';lc='Variable cost / customer';o=`${Math.ceil(a/Math.max(.01,b-c))} customers`}return <Split left={<><Num label={la} value={a} set={sa} step={.01}/><Num label={lb} value={b} set={sb} step={.01}/>{lc&&<Num label={lc} value={c} set={sc} step={.01}/>}</>} right={<Output value={o}/>}/>}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number.isFinite(n)?n:0);

const R:Record<string,()=>React.ReactNode>={'favicon-generator':()=> <Favicon/>,'svg-optimizer':()=> <SvgOptimizer/>,'shadow-generator':()=> <Shadow/>,'regex-tester':()=> <Regex/>,'hash-generator':()=> <Hash/>,'opengraph-preview':()=> <OG/>,'meta-tags':()=> <Meta/>,'robots-txt':()=> <Robots/>,'json-ld':()=> <JsonLd/>,'utm-builder':()=> <UTM/>,'curl-converter':()=> <Curl/>,'http-status':()=> <Status/>,'jsonpath-tester':()=> <JsonPath/>,'headers-inspector':()=> <Headers/>,'webhook-tester':()=> <Webhook/>,'csv-json':()=> <Csv/>,'yaml-json':()=> <Yaml/>,'xml-json':()=> <Xml/>,'sql-formatter':()=> <Sql/>,'fake-data':()=> <Fake/>,'mrr-calculator':()=> <Calc kind="mrr"/>,'arr-calculator':()=> <Calc kind="arr"/>,'churn-calculator':()=> <Calc kind="churn"/>,'ltv-calculator':()=> <Calc kind="ltv"/>,'pricing-calculator':()=> <Calc kind="pricing"/>,'stripe-fees':()=> <Calc kind="stripe"/>,'break-even':()=> <Calc kind="break-even"/>};
export default function Lab(){const r=useRouter(),id=typeof r.query.tool==='string'?r.query.tool:'regex-tester',tool=tools.find(t=>t.id===id),render=R[id],[q,sq]=useState(''),list=tools.filter(t=>t.href?.startsWith('/lab')).filter(t=>`${t.name} ${t.category}`.toLowerCase().includes(q.toLowerCase()));return <><Head><title>{tool?.name||'Tool'} — indieTools</title></Head><main className="app-shell"><header className="topbar"><Link href="/" className="brand"><div className="brand-mark">iT</div><div><div>indieTools</div><div className="brand-sub">builder toolbox</div></div></Link><Link href="/" className="ghost-btn"><ArrowLeft size={14}/> All tools</Link></header><section className="workspace"><aside className="sidebar"><div className="search"><Search size={16}/><input placeholder="Search tools..." value={q} onChange={e=>sq(e.target.value)}/></div><div className="tool-list" style={{marginTop:12}}>{list.map(t=><Link key={t.id} href={`/lab?tool=${t.id}`} className={`tool-item ${t.id===id?'active':''}`}><span><strong>{t.name}</strong><small>{t.category}</small></span></Link>)}</div></aside><section className="tool-stage"><div className="tool-head"><div><h2>{tool?.name}</h2><p>{tool?.description}</p></div><span className="tool-badge">Runs locally</span></div><div className="tool-body">{render?render():<div className="empty-state">Tool not found.</div>}</div></section></section></main></>}
